# Generated by Django 5.2.17 on 2026-08-31 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A friendly name for this job', max_length=255)),
                ('url', models.URLField(help_text='The URL to scrape', max_length=2000)),
                ('css_selector', models.CharField(help_text='CSS selector to target elements (e.g. h1, .title, #main p)', max_length=500)),
                ('extract_attribute', models.CharField(blank=True, default='text', help_text='Attribute to extract: "text" for inner text, or an HTML attribute like "href", "src"', max_length=100)),
                ('headers', models.TextField(blank=True, default='', help_text='Optional extra HTTP headers in JSON format (e.g. {"Accept-Language": "en-US"})')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scrape Job',
                'verbose_name_plural': 'Scrape Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The scraped text or attribute value')),
                ('element_tag', models.CharField(blank=True, default='', max_length=50)),
                ('element_index', models.PositiveIntegerField(default=0)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scraper.scrapejob')),
            ],
            options={
                'verbose_name': 'Scrape Result',
                'verbose_name_plural': 'Scrape Results',
                'ordering': ['element_index'],
            },
        ),
    ]
